import { dirname, join, resolve, relative } from 'path';
import { fileURLToPath } from 'url';
import { existsSync, readFileSync } from 'fs';
import { extract, expand, type MergerFn } from '@tailwind-expand/core';

const __dirname = dirname(fileURLToPath(import.meta.url));
const absolutePath = resolve(join(__dirname, '..', 'tailwind_expand_swc.wasm'));

// Use relative path for Turbopack compatibility (https://github.com/vercel/next.js/issues/78156)
const wasmPath = relative(process.cwd(), absolutePath);

// Default cache location for PostCSS-generated aliases
const DEFAULT_ALIASES_PATH = '.next/dev/cache/tailwind-expand/aliases.json';

export interface SwcPluginOptions {
  /**
   * Path to the CSS file containing @expand definitions.
   * Used to extract and expand aliases at config time.
   */
  cssPath: string;

  /**
   * Optional function to merge conflicting Tailwind utilities.
   * If provided, utilities like "py-2 py-4" will be merged to just "py-4".
   * Recommended: use `twMerge` from 'tailwind-merge' package.
   */
  mergerFn?: MergerFn;
}

/**
 * Parses aliases from a generated JSON file.
 * The file format is expected to be generated by @tailwind-expand/postcss.
 */
function parseAliasesFile(filePath: string): Record<string, string> | null {
  if (!existsSync(filePath)) {
    return null;
  }

  try {
    const content = readFileSync(filePath, 'utf-8');
    const aliases = JSON.parse(content) as Record<string, string>;
    return Object.keys(aliases).length > 0 ? aliases : null;
  } catch {
    return null;
  }
}

/**
 * Creates an SWC plugin configuration for tailwind-expand.
 *
 * Transforms className="Button" → className="text-xs font-bold ..."
 *
 * For HMR support in development, only include this plugin in production builds.
 * PostCSS will generate CSS classes (.Button { ... }) for development.
 *
 * Works with any SWC-based tool:
 * - Next.js (Turbopack)
 * - swc-loader (Webpack)
 * - @swc/core
 * - Rspack
 *
 * @example
 * ```js
 * // next.config.js - Production only for HMR support
 * import tailwindExpandSWC from '@tailwind-expand/swc';
 * import { twMerge } from 'tailwind-merge';
 *
 * const isProd = process.env.NODE_ENV === 'production';
 *
 * export default {
 *   experimental: {
 *     swcPlugins: isProd
 *       ? [tailwindExpandSWC({ cssPath: './app/globals.css', mergerFn: twMerge })]
 *       : []
 *   }
 * }
 * ```
 */
export default function tailwindExpandSWC(
  options: SwcPluginOptions
): [string, { aliases: Record<string, string> }] {
  const { cssPath, mergerFn } = options;

  // Try to read from pre-generated aliases file first
  const aliasesPath = resolve(DEFAULT_ALIASES_PATH);
  const cachedAliases = parseAliasesFile(aliasesPath);

  let aliases: Record<string, string>;

  if (cachedAliases) {
    // Use pre-generated aliases from PostCSS
    aliases = cachedAliases;
  } else {
    // Fall back to extracting from CSS
    const absoluteCssPath = resolve(cssPath);
    const { aliases: rawAliases } = extract(absoluteCssPath);
    aliases = expand(rawAliases, { mergerFn });
  }

  return [wasmPath, { aliases }];
}
